name: Generate Screenshot Every 3 Days

on:
  schedule:
    - cron: "0 0 */3 * *"  # Run every 3 days at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"  # Use the latest LTS version

      - name: Install dependencies
        run: npm install puppeteer

      - name: Create screenshot script
        run: |
          echo "const puppeteer = require('puppeteer');
          const fs = require('fs').promises;

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.setViewport({ width: 1920, height: 1080 });
            await page.goto('https://letterboxd-embed.lrsayed.workers.dev/?username=abusayed', { waitUntil: 'networkidle0' });
            await page.screenshot({ path: 'film.jpg', type: 'jpeg', quality: 70, fullPage: false });
            await browser.close();

            const stats = await fs.stat('film.jpg');
            console.log('Image file size:', stats.size, 'bytes');
            if (stats.size === 0) {
              throw new Error('Image file is empty');
            }
          })();" > screenshot.js

      - name: Run screenshot script
        run: node screenshot.js

      - name: Upload screenshot as artifact
        uses: actions/upload-artifact@v4
        with:
          name: film-screenshot
          path: film.jpg

      - name: Clean up temporary files
        run: rm screenshot.js
