name: Generate and Upload Screenshot

on:
  schedule:
    - cron: "0 0 */3 * *"  # Run every 3 days at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install puppeteer

      - name: Create screenshot script
        run: |
          echo "const puppeteer = require('puppeteer');
          const fs = require('fs').promises;

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.setViewport({ width: 1920, height: 1080 });
            await page.goto('https://letterboxd-embed.lrsayed.workers.dev/?username=abusayed', { waitUntil: 'networkidle0' });
            await page.screenshot({ path: 'film.jpg', type: 'jpeg', quality: 70 });
            await browser.close();

            const stats = await fs.stat('film.jpg');
            console.log('Image file size:', stats.size, 'bytes');
            if (stats.size === 0) {
              throw new Error('Image file is empty');
            }
          })();" > screenshot.js

      - name: Run screenshot script
        run: node screenshot.js

      - name: Upload screenshot as release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'latest'  # You can also use a dynamic tag based on the date or version
          release_name: 'Film Screenshot - $(date +'%Y-%m-%d')'
          files: film.jpg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up temporary files
        run: rm screenshot.js
