name: Commit Screenshot to Repository

on:
  workflow_run:
    workflows: ["Generate and Upload Screenshot"]  # Specify the name of the first workflow
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download the latest release asset
        id: download_asset
        run: |
          # Get the latest release asset URL for film.jpg
          RELEASE_DATA=$(curl -s "https://api.github.com/repos/abusayed0206/film-page-screenshot/releases/latest")
          ASSET_URL=$(echo $RELEASE_DATA | jq -r '.assets[] | select(.name=="film.jpg") | .url')
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o film.jpg $ASSET_URL

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        run: |
          git add film.jpg
          git commit -m "Update screenshot for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
